baseURL = 'https://worldenddisk.com/'
languageCode = 'en-gb'
title = 'Ada Null'
disableKinds = ['section', 'taxonomy', 'term']

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.parser]
            wrapStandAloneImageWithinParagraph = false