baseURL = 'https://worldenddisk.com/'
languageCode = 'en-gb'
title = 'Ada Null'
disableKinds = ['section', 'taxonomy', 'term']

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.parser]
            wrapStandAloneImageWithinParagraph = false

[menus]
    [[menus.main]]
        name = "About"
        pageRef = "/"
    [[menus.main]]
        name = "CV"
        pageRef = "cv"
    [[menus.main]]
        name = "Source code"
        url = "https://github.com/linky00/worldenddisk"

[params]
    imgFit = "1920x1920 jpg"