baseURL = 'https://worldenddisk.com/'
languageCode = 'en-gb'
title = 'Ada Null'
disableKinds = ['section', 'taxonomy', 'term']

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.parser]
            wrapStandAloneImageWithinParagraph = false

[menus]
    [[menus.main]]
        name = "About"
        pageRef = "/"
    [[menus.main]]
        name = "CV"
        pageRef = "cv"
    [[menus.main]]
        name = "Instagram"
        url = "https://www.instagram.com/worldenddisk/"
        [menus.main.params]
            external = true
    [[menus.main]]
        name = "Email"
        url = "mailto:ada@worldenddisk.com"
        [menus.main.params]
            external = true
    [[menus.main]]
        name = "Site source"
        url = "https://github.com/linky00/worldenddisk"
        [menus.main.params]
            external = true

[params]
    imgFit = "1920x1920 jpg"