name: Deploy Hugo site to Linode

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.124.1
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo --minify
      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.0
        with:
          switches: -avzr --delete
          path: public/
          remote_path: /var/www/html/
          remote_host: worldenddisk.com
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}
